import { NationalityToCountryCode } from "../types";

export const teamColors: { [key: string]: { from: string; to: string } } = {
  red_bull: { from: "#1e40af", to: "#1e293b" },
  mercedes: { from: "#00D2BE", to: "#115e59" },
  ferrari: { from: "#ef4444", to: "#991b1b" },
  mclaren: { from: "#f97316", to: "#9a3412" },
  alpine: { from: "#ec4899", to: "#9d174d" },
  aston_martin: { from: "#10b981", to: "#065f46" },
  alpha_tauri: { from: "#64748b", to: "#1e293b" },
  haas: { from: "#f43f5e", to: "#9f1239" },
  williams: { from: "#0284c7", to: "#0c4a6e" },
  racing_point: { from: "#ec4899", to: "#9d174d" },
  renault: { from: "#eab308", to: "#854d0e" },
  kick_sauber: { from: "#22c55e", to: "#166534" },
  rb: { from: "#6366f1", to: "#3730a3" },
  default: { from: "#ef4444", to: "#991b1b" },
  force_india: { from: "#4ade80", to: "#fb923c" },
};

export const nationalityToCountryCode: NationalityToCountryCode = {
  American: "us",
  British: "gb",
  Canadian: "ca",
  French: "fr",
  German: "de",
  Italian: "it",
  Japanese: "jp",
  Mexican: "mx",
  Russian: "ru",
  Spanish: "es",
  Australian: "au",
  Chinese: "cn",
  Brazilian: "br",
  Indian: "in",
  "South African": "za",
  "South Korean": "kr",
  Dutch: "nl",
  Swedish: "se",
  Swiss: "ch",
  Belgian: "be",
  Portuguese: "pt",
  Argentinian: "ar",
  Argentine: "ar",
  Chilean: "cl",
  Colombian: "co",
  Turkish: "tr",
  Polish: "pl",
  Norwegian: "no",
  Danish: "dk",
  Finnish: "fi",
  Austrian: "at",
  Irish: "ie",
  Israeli: "il",
  "Saudi Arabian": "sa",
  UAE: "ae",
  Singaporean: "sg",
  Malaysian: "my",
  Thai: "th",
  "New Zealander": "nz",
  Hungarian: "hu",
  Czech: "cz",
  Slovak: "sk",
  Romanian: "ro",
  Bulgarian: "bg",
  Greek: "gr",
  Cypriot: "cy",
  Lithuanian: "lt",
  Latvian: "lv",
  Estonian: "ee",
  Serbian: "rs",
  Croatian: "hr",
  Slovenian: "si",
  Montenegrin: "me",
  Bosnian: "ba",
  Macedonian: "mk",
  Albanian: "al",
  Icelandic: "is",
  Luxembourgish: "lu",
  Liechtenstein: "li",
  Andorran: "ad",
  Monegasque: "mc",
  "San Marinese": "sm",
  Vatican: "va",
  Palestinian: "ps",
  Jordanian: "jo",
  Lebanese: "lb",
  Kuwaiti: "kw",
  Omani: "om",
  Yemeni: "ye",
  Libyan: "ly",
  Moroccan: "ma",
  Algerian: "dz",
  Tunisian: "tn",
  Sudanese: "sd",
  Ethiopian: "et",
  Kenyan: "ke",
  Nigerian: "ng",
  Ghanaian: "gh",
  "Ivory Coast": "ci",
  Senegalese: "sn",
  Malian: "ml",
  Burkinabe: "bf",
  Zambian: "zm",
  Zimbabwean: "zw",
  Angolan: "ao",
  Namibian: "na",
  Botswana: "bw",
  Mozambican: "mz",
  Swazi: "sz",
  Lesotho: "ls",
  Rwandan: "rw",
  Burundian: "bi",
  Congolese: "cd",
  "Central African": "cf",
  Gabonese: "ga",
  Chadian: "td",
  Cameroonian: "cm",
  Mauritian: "mu",
  Seychellois: "sc",
  Djiboutian: "dj",
  Eritrean: "er",
  "South Sudanese": "ss",
  "Venezuelan": "ve",
  Uruguayan: 'uy'
};

export const mapOptions = {
  zoomControl: false,
  scrollWheelZoom: false, // Disable zooming with the mouse wheel
  doubleClickZoom: false, // Disable zooming on double click
  touchZoom: false, // Disable zooming with pinch gestures
  dragging: false, // Optionally disable dragging
};

export const randomColors = [
  { from: "#1e40af", to: "#1e293b" },
  { from: "#00D2BE", to: "#115e59" },
  { from: "#ef4444", to: "#991b1b" },
  { from: "#f97316", to: "#9a3412" },
  { from: "#ec4899", to: "#9d174d" },
  { from: "#10b981", to: "#065f46" },
  { from: "#64748b", to: "#1e293b" },
  { from: "#0c4a6e", to: "#0284c7" },
  { from: "#eab308", to: "#854d0e" },
  { from: "#22c55e", to: "#166534" },
  { from: "#6366f1", to: "#3730a3" },
  { from: "#d97706", to: "#7c2d12" },
  { from: "#6b21a8", to: "#581c87" },
  { from: "#f43f5e", to: "#9f1239" },
  { from: "#3b82f6", to: "#1e3a8a" },
  { from: "#34d399", to: "#064e3b" },
  { from: "#8b5cf6", to: "#5b21b6" },
  { from: "#f59e0b", to: "#b45309" },
  { from: "#0ea5e9", to: "#0369a1" },
  { from: "#a3e635", to: "#65a30d" },
  { from: "#9333ea", to: "#4c1d95" },
  { from: "#ff9800", to: "#e65100" },
  { from: "#009688", to: "#004d40" },
  { from: "#f06292", to: "#c2185b" },
];
