import { NationalityToCountryCode } from "./types";

export const teamColors = {
  red_bull: {from: "#1E41FF", to: '#1e293b'},
  mercedes: {from: "#00D2BE", to: '#115e59'},
  ferrari: {from: "#DC0000", to: '#991b1b'},
  mclaren: {from: "#FF8700", to: '#9a3412'},
  alpine: "#0090FF",
  aston_martin: "#006F62",
  alpha_tauri: "#002A72",
  haas: "#F1F1F1",
  williams: "#0056A0",
  alfa_romeo: "#900000",
};

export const nationalityToCountryCode: NationalityToCountryCode = {
  American: "us",
  British: "gb",
  Canadian: "ca",
  French: "fr",
  German: "de",
  Italian: "it",
  Japanese: "jp",
  Mexican: "mx",
  Russian: "ru",
  Spanish: "es",
  Australian: "au",
  Chinese: "cn",
  Brazilian: "br",
  Indian: "in",
  "South African": "za",
  "South Korean": "kr",
  Dutch: "nl",
  Swedish: "se",
  Swiss: "ch",
  Belgian: "be",
  Portuguese: "pt",
  Argentinian: "ar",
  Chilean: "cl",
  Colombian: "co",
  Turkish: "tr",
  Polish: "pl",
  Norwegian: "no",
  Danish: "dk",
  Finnish: "fi",
  Austrian: "at",
  Irish: "ie",
  Israeli: "il",
  "Saudi Arabian": "sa",
  UAE: "ae",
  Singaporean: "sg",
  Malaysian: "my",
  Thai: "th",
  "New Zealander": "nz",
  Hungarian: "hu",
  Czech: "cz",
  Slovak: "sk",
  Romanian: "ro",
  Bulgarian: "bg",
  Greek: "gr",
  Cypriot: "cy",
  Lithuanian: "lt",
  Latvian: "lv",
  Estonian: "ee",
  Serbian: "rs",
  Croatian: "hr",
  Slovenian: "si",
  Montenegrin: "me",
  Bosnian: "ba",
  Macedonian: "mk",
  Albanian: "al",
  Icelandic: "is",
  Luxembourgish: "lu",
  Liechtenstein: "li",
  Andorran: "ad",
  Monegasque: "mc",
  "San Marinese": "sm",
  Vatican: "va",
  Palestinian: "ps",
  Jordanian: "jo",
  Lebanese: "lb",
  Kuwaiti: "kw",
  Omani: "om",
  Yemeni: "ye",
  Libyan: "ly",
  Moroccan: "ma",
  Algerian: "dz",
  Tunisian: "tn",
  Sudanese: "sd",
  Ethiopian: "et",
  Kenyan: "ke",
  Nigerian: "ng",
  Ghanaian: "gh",
  "Ivory Coast": "ci",
  Senegalese: "sn",
  Malian: "ml",
  Burkinabe: "bf",
  Zambian: "zm",
  Zimbabwean: "zw",
  Angolan: "ao",
  Namibian: "na",
  Botswana: "bw",
  Mozambican: "mz",
  Swazi: "sz",
  Lesotho: "ls",
  Rwandan: "rw",
  Burundian: "bi",
  Congolese: "cd",
  "Central African": "cf",
  Gabonese: "ga",
  Chadian: "td",
  Cameroonian: "cm",
  Mauritian: "mu",
  Seychellois: "sc",
  Djiboutian: "dj",
  Eritrean: "er",
  "South Sudanese": "ss",
};
