import type { Metadata } from "next";
import "./globals.css";
import { defaults } from "chart.js";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  defaults.font.family = "f-bold";
  return (
    <html lang="en">
      <body className="px-8">{children}</body>
    </html>
  );
}
